server:
  port: 10001
spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/db_common_springboot?useUnicode=TRUE&characterEncoding=utf-8&useSSL=FALSE&serverTimezone=GMT%2B8
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
      #max-active: 10
      #initial-size: 10
