server:
  port: 10001
spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/db_common_springboot?useUnicode=true&amp;characterEncoding=utf-8&amp;useSSL=false
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
      #max-active: 10
      #initial-size: 10
